// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn1pWjyUAV1Ne4NB3jmO50ZOvIuv1CnC8',
    appId: '1:1082171256626:web:68cf0300897b993958312b',
    messagingSenderId: '1082171256626',
    projectId: 'gdgcapstoneproject-2025',
    authDomain: 'gdgcapstoneproject-2025.firebaseapp.com',
    storageBucket: 'gdgcapstoneproject-2025.firebasestorage.app',
    measurementId: 'G-B3CNWB7M3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Nth3425Km7yC-QbeES2Dm2VK8Gb1RA8',
    appId: '1:1082171256626:android:3062b2c4d181f1ec58312b',
    messagingSenderId: '1082171256626',
    projectId: 'gdgcapstoneproject-2025',
    storageBucket: 'gdgcapstoneproject-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbaFGDxcovdG86ubVStArBDqNskfjeHFU',
    appId: '1:1082171256626:ios:80750dcc56aeaa5258312b',
    messagingSenderId: '1082171256626',
    projectId: 'gdgcapstoneproject-2025',
    storageBucket: 'gdgcapstoneproject-2025.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbaFGDxcovdG86ubVStArBDqNskfjeHFU',
    appId: '1:1082171256626:ios:80750dcc56aeaa5258312b',
    messagingSenderId: '1082171256626',
    projectId: 'gdgcapstoneproject-2025',
    storageBucket: 'gdgcapstoneproject-2025.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn1pWjyUAV1Ne4NB3jmO50ZOvIuv1CnC8',
    appId: '1:1082171256626:web:7c8c4d2db3a470da58312b',
    messagingSenderId: '1082171256626',
    projectId: 'gdgcapstoneproject-2025',
    authDomain: 'gdgcapstoneproject-2025.firebaseapp.com',
    storageBucket: 'gdgcapstoneproject-2025.firebasestorage.app',
    measurementId: 'G-XRZEJBW6L0',
  );

}