// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9iWkomUpcWGgMAnfxPAtAPFUh7vK5Kk',
    appId: '1:964682230485:web:7cd937674e54b2e8c0505c',
    messagingSenderId: '964682230485',
    projectId: 'capstone-621c0',
    authDomain: 'capstone-621c0.firebaseapp.com',
    storageBucket: 'capstone-621c0.firebasestorage.app',
    measurementId: 'G-6KZ1TN8QSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmvs00VOaxizOn1AZRwa930thU-7JxIMM',
    appId: '1:964682230485:android:c7dc5f10da0bc174c0505c',
    messagingSenderId: '964682230485',
    projectId: 'capstone-621c0',
    storageBucket: 'capstone-621c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIhNzlewl_SFAOF9putX5RQYz3LC0jbeg',
    appId: '1:964682230485:ios:c8c56729975a391fc0505c',
    messagingSenderId: '964682230485',
    projectId: 'capstone-621c0',
    storageBucket: 'capstone-621c0.firebasestorage.app',
    iosBundleId: 'com.example.capstoneLandingPageProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIhNzlewl_SFAOF9putX5RQYz3LC0jbeg',
    appId: '1:964682230485:ios:c8c56729975a391fc0505c',
    messagingSenderId: '964682230485',
    projectId: 'capstone-621c0',
    storageBucket: 'capstone-621c0.firebasestorage.app',
    iosBundleId: 'com.example.capstoneLandingPageProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS9iWkomUpcWGgMAnfxPAtAPFUh7vK5Kk',
    appId: '1:964682230485:web:77f9f8a572f0b74ac0505c',
    messagingSenderId: '964682230485',
    projectId: 'capstone-621c0',
    authDomain: 'capstone-621c0.firebaseapp.com',
    storageBucket: 'capstone-621c0.firebasestorage.app',
    measurementId: 'G-SXVB9BHG4J',
  );
}
